image: Visual Studio 2017

# version format
version: 1.0.0.{build}

# UMBRACO_PACKAGE_PRERELEASE_SUFFIX if a rtm release build this should be blank, otherwise if empty will default to alpha
# example UMBRACO_PACKAGE_PRERELEASE_SUFFIX=beta
init:
  - set UMBRACO_PACKAGE_PRERELEASE_SUFFIX=

cache:
  - src\packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

before_build:
  - nuget restore src

build_script:
- build-appveyor.cmd

artifacts:
  - path: artifacts\*.nupkg
  - path: artifacts\*.zip

deploy:
    # GitHub Deployment for releases
  - provider: GitHub
    auth_token:
      secure: JmLktqm0owpfktMIINBjo3CKr9S/53yhtFypcz6WefhozE77x0PJvJ0zr+1/rLER
    artifact: /.*\.zip/            # upload all Zip packages to release assets
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true        # deploy on tag push only

    # NuGet Deployment for releases
  - provider: NuGet
    server: 
    api_key:
      secure: DLHhnOs1WWsZlHnkId7symdMXDvqDo8+SS3w9M+TDsd2vAfqvhdtN/aMcLq7M9+y
    artifact: /.*\.nupkg/
    on:
      branch: master
      appveyor_repo_tag: true
